projects:
  bunker:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
      - aws_directives.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
